### ISSUE TITLE
web1 start error

### ISSUE THREAD

**Issue by meteorlad** [MoePlayer/DPlayer-node#1]
exec `docker-compose up` output log：

```
redis_1  | 1:M 08 Jul 15:37:26.860 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1  | 1:M 08 Jul 15:37:26.860 * DB loaded from disk: 0.000 seconds
redis_1  | 1:M 08 Jul 15:37:26.860 * Ready to accept connections
web_1    | [2018-07-08T15:37:28.135Z] PM2 log: Launching in no daemon mode
mongo_1  | 2018-07-08T15:37:28.162+0000 I STORAGE  [initandlisten] WiredTiger message [1531064248:162785][1:0x7f495e3b3a00], txn-recover: Main recovery loop: starting at 3/6912
mongo_1  | 2018-07-08T15:37:28.283+0000 I STORAGE  [initandlisten] WiredTiger message [1531064248:283646][1:0x7f495e3b3a00], txn-recover: Recovering log 3 through 4
web_1    | [2018-07-08T15:37:28.292Z] PM2 log: Starting execution sequence in -fork mode- for app name:index id:0
web_1    | [2018-07-08T15:37:28.319Z] PM2 log: App name:index id:0 online
mongo_1  | 2018-07-08T15:37:28.382+0000 I STORAGE  [initandlisten] WiredTiger message [1531064248:382178][1:0x7f495e3b3a00], txn-recover: Recovering log 4 through 4
mongo_1  | 2018-07-08T15:37:28.460+0000 I STORAGE  [initandlisten] WiredTiger message [1531064248:460439][1:0x7f495e3b3a00], txn-recover: Set global recovery timestamp: 0
mongo_1  | 2018-07-08T15:37:28.470+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo_1  | 2018-07-08T15:37:28.494+0000 I CONTROL  [initandlisten]
mongo_1  | 2018-07-08T15:37:28.494+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1  | 2018-07-08T15:37:28.494+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1  | 2018-07-08T15:37:28.494+0000 I CONTROL  [initandlisten]
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten]
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten]
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo_1  | 2018-07-08T15:37:28.495+0000 I CONTROL  [initandlisten]
mongo_1  | 2018-07-08T15:37:28.523+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1  | 2018-07-08T15:37:28.529+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
web_1    | /usr/src/app/node_modules/koa-bodyparser/index.js:72
web_1    |   return async function bodyParser(ctx, next) {
web_1    |                ^^^^^^^^
web_1    | SyntaxError: Unexpected token function
web_1    |     at createScript (vm.js:56:10)
web_1    |     at Object.runInThisContext (vm.js:97:10)
web_1    |     at Module._compile (module.js:549:28)
web_1    |     at Object.Module._extensions..js (module.js:586:10)
web_1    |     at Module.load (module.js:494:32)
web_1    |     at tryModuleLoad (module.js:453:12)
web_1    |     at Function.Module._load (module.js:445:3)
web_1    |     at Module.require (module.js:504:17)
web_1    |     at require (internal/module.js:20:19)
web_1    |     at Object.<anonymous> (/usr/src/app/index.js:2:20)
web_1    | [2018-07-08T15:37:28.711Z] PM2 log: App [index] with id [0] and pid [15], exited with code [1] via signal [SIGINT]
web_1    | [2018-07-08T15:37:28.714Z] PM2 log: Starting execution sequence in -fork mode- for app name:index id:0
web_1    | [2018-07-08T15:37:28.724Z] PM2 log: App name:index id:0 online
web_1    | /usr/src/app/node_modules/koa-bodyparser/index.js:72
web_1    |   return async function bodyParser(ctx, next) {
web_1    |                ^^^^^^^^
web_1    | SyntaxError: Unexpected token function
web_1    |     at createScript (vm.js:56:10)
web_1    |     at Object.runInThisContext (vm.js:97:10)
web_1    |     at Module._compile (module.js:549:28)
web_1    |     at Object.Module._extensions..js (module.js:586:10)
web_1    |     at Module.load (module.js:494:32)
web_1    |     at tryModuleLoad (module.js:453:12)
web_1    |     at Function.Module._load (module.js:445:3)
web_1    |     at Module.require (module.js:504:17)
web_1    |     at require (internal/module.js:20:19)
web_1    |     at Object.<anonymous> (/usr/src/app/index.js:2:20)
web_1    | [2018-07-08T15:37:29.021Z] PM2 log: App [index] with id [0] and pid [41], exited with code [1] via signal [SIGINT]
web_1    | [2018-07-08T15:37:29.026Z] PM2 log: Starting execution sequence in -fork mode- for app name:index id:0
web_1    | [2018-07-08T15:37:29.035Z] PM2 log: App name:index id:0 online
web_1    | /usr/src/app/node_modules/koa-bodyparser/index.js:72
web_1    |   return async function bodyParser(ctx, next) {
```

**Comment by meteorlad** [comment]
The problem has been solved！

**Comment by Sokwva** [comment]
Excuse me ，I want to know that how do you solve the problem.

**Comment by Sokwva** [comment]
Excuse me ，I want to know that how do you solve the problem.
