### ISSUE TITLE
能否提供以下mongo的初始化脚本

### ISSUE THREAD

**Issue by iqolome** [MoePlayer/DPlayer-node#7]
## 已经有mongo和redis了,想放在一起,现在pm2直接启动连接报这个错 

```log
0|index  | error: Promise error: TypeError: Cannot read property 'cid' of undefined
0|index  |     at module.exports (/server/DPlayer-node/routes/bilibili.js:13:29)
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|index  |     at async module.exports (/server/DPlayer-node/middleware/access-control.js:12:9)
0|index  |     at async module.exports (/server/DPlayer-node/middleware/header.js:13:5)
0|index  |     at async module.exports (/server/DPlayer-node/middleware/onerror.js:5:9)
0|index  |     at async bodyParser (/server/DPlayer-node/node_modules/koa-bodyparser/index.js:86:5)
0|index  | info: /v3/, user IP: ::ffff:192.168.1.10


```

**Comment by iqolome** [comment]
找到问题了,不是monggo的问题.是密码里面有@导致的
